/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ENTRYPOINT: typeof import('./graphql/config').ENTRYPOINT
  const ENTRYPOINT_GRAPHQL: typeof import('./graphql/config').ENTRYPOINT_GRAPHQL
  const EffectScope: typeof import('vue').EffectScope
  const Entity: typeof import('./models/useEntityFactory').Entity
  const SubmissionError: typeof import("./utils/error").SubmissionError
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const api: typeof import('./services/api').default
  const apollo: typeof import('./graphql/api').apollo
  const apolloClient: typeof import('./graphql/apolloClient').apolloClient
  const b: typeof import('./services/bus').b
  const bus: typeof import('./services/bus').bus
  const cformat: typeof import("./utils/date copy").cformat
  const cl: typeof import('./utils/autoimport/miscellaneous').cl
  const cle: typeof import('./utils/autoimport/miscellaneous').cle
  const cloading: typeof import('./utils/autoimport/miscellaneous').cloading
  const cls: typeof import('./utils/autoimport/miscellaneous').cls
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const createStore: typeof import('./stores/useStore').createStore
  const customRef: typeof import('vue').customRef
  const dayjs: typeof import("./utils/date copy").dayjs
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const dformat: typeof import("./utils/date copy").dformat
  const effectScope: typeof import('vue').effectScope
  const extractHubURL: typeof import("./utils/mercure").extractHubURL
  const fdn: typeof import('./models/useEntityFactory').fdn
  const formatDateInput: typeof import("./utils/date").formatDateInput
  const formatDateTime: typeof import("./utils/date").formatDateTime
  const getActivePinia: typeof import('pinia').getActivePinia
  const getAlertText: typeof import('./utils/autoimport/miscellaneous').getAlertText
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const gloading: typeof import('./utils/autoimport/miscellaneous').gloading
  const h: typeof import('vue').h
  const highlighted: typeof import('./utils/autoimport/miscellaneous').highlighted
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const logSQL: typeof import('./utils/autoimport/miscellaneous').logSQL
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const mercureSubscribe: typeof import("./utils/mercure").mercureSubscribe
  const merror: typeof import('./services/bus').merror
  const minfo: typeof import('./services/bus').minfo
  const mloading: typeof import('./utils/autoimport/miscellaneous').mloading
  const month_day_hour_format: typeof import("./utils/date copy").month_day_hour_format
  const msuccess: typeof import('./services/bus').msuccess
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const qloading: typeof import('./utils/autoimport/miscellaneous').qloading
  const random: typeof import('./utils/autoimport/miscellaneous').random
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const storeToRefs: typeof import('pinia').storeToRefs
  const stores: typeof import('./stores/index').default
  const str: typeof import('./utils/autoimport/miscellaneous').str
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const treeKey: typeof import('./utils/autoimport/miscellaneous').treeKey
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useApollo: typeof import('./composables/useApollo').useApollo
  const useAttrs: typeof import('vue').useAttrs
  const useBreadcrumb: typeof import('./composables/breadcrumb').useBreadcrumb
  const useBus: typeof import('./composables/useBus').useBus
  const useCounterStore: typeof import('./stores/example-store').useCounterStore
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useMenuStateStore: typeof import('./stores/ui/menu').useMenuStateStore
  const useMercureItem: typeof import('./composables/mercureItem').useMercureItem
  const useMercureList: typeof import('./composables/mercureList').useMercureList
  const useMetadataStore: typeof import('./stores/metadata').useMetadataStore
  const useModel: typeof import('vue').useModel
  const useNotifications: typeof import('./composables/notifications').useNotifications
  const usePermisoCreateStore: typeof import('./stores/permiso/create').usePermisoCreateStore
  const usePermisoDeleteStore: typeof import('./stores/permiso/delete').usePermisoDeleteStore
  const usePermisoListStore: typeof import('./stores/permiso/list').usePermisoListStore
  const usePermisoShowStore: typeof import('./stores/permiso/show').usePermisoShowStore
  const usePermisoUpdateStore: typeof import('./stores/permiso/update').usePermisoUpdateStore
  const useQuasar: typeof import('quasar').useQuasar
  const useRoleCreateStore: typeof import('./stores/role/create').useRoleCreateStore
  const useRoleDeleteStore: typeof import('./stores/role/delete').useRoleDeleteStore
  const useRoleListStore: typeof import('./stores/role/list').useRoleListStore
  const useRoleShowStore: typeof import('./stores/role/show').useRoleShowStore
  const useRoleUpdateStore: typeof import('./stores/role/update').useRoleUpdateStore
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSidebarStore: typeof import('./stores/ui/sidebar').useSidebarStore
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useThemeStateStore: typeof import('./stores/ui/ThemeState').useThemeStateStore
  const useUserCreateStore: typeof import('./stores/user/create').useUserCreateStore
  const useUserDeleteStore: typeof import('./stores/user/delete').useUserDeleteStore
  const useUserListStore: typeof import('./stores/user/list').useUserListStore
  const useUserSessionStore: typeof import('./stores/session').useUserSessionStore
  const useUserShowStore: typeof import('./stores/user/show').useUserShowStore
  const useUserUpdateStore: typeof import('./stores/user/update').useUserUpdateStore
  const useWatchErrors: typeof import('./composables/errors').useWatchErrors
  const user: typeof import('./models/useEntityFactory').user
  const util: typeof import('./utils/autoimport/miscellaneous').util
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { PiniaCustomProperties } from './stores/index'
  import('./stores/index')
  // @ts-ignore
  export type { Menu } from './stores/ui/menu'
  import('./stores/ui/menu')
  // @ts-ignore
  export type { SidebarState } from './stores/ui/sidebar'
  import('./stores/ui/sidebar')
  // @ts-ignore
  export type { Entity } from './models/useEntityFactory'
  import('./models/useEntityFactory')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ENTRYPOINT: UnwrapRef<typeof import('./graphql/config')['ENTRYPOINT']>
    readonly ENTRYPOINT_GRAPHQL: UnwrapRef<typeof import('./graphql/config')['ENTRYPOINT_GRAPHQL']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly Entity: UnwrapRef<typeof import('./models/useEntityFactory')['Entity']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly api: UnwrapRef<typeof import('./services/api')['default']>
    readonly apollo: UnwrapRef<typeof import('./graphql/api')['apollo']>
    readonly apolloClient: UnwrapRef<typeof import('./graphql/apolloClient')['apolloClient']>
    readonly b: UnwrapRef<typeof import('./services/bus')['b']>
    readonly bus: UnwrapRef<typeof import('./services/bus')['bus']>
    readonly cl: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['cl']>
    readonly cle: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['cle']>
    readonly cloading: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['cloading']>
    readonly cls: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['cls']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createStore: UnwrapRef<typeof import('./stores/useStore')['createStore']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly fdn: UnwrapRef<typeof import('./models/useEntityFactory')['fdn']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getAlertText: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['getAlertText']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly gloading: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['gloading']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly highlighted: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['highlighted']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly logSQL: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['logSQL']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly merror: UnwrapRef<typeof import('./services/bus')['merror']>
    readonly minfo: UnwrapRef<typeof import('./services/bus')['minfo']>
    readonly mloading: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['mloading']>
    readonly msuccess: UnwrapRef<typeof import('./services/bus')['msuccess']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly qloading: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['qloading']>
    readonly random: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['random']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly stores: UnwrapRef<typeof import('./stores/index')['default']>
    readonly str: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['str']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly treeKey: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['treeKey']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useApollo: UnwrapRef<typeof import('./composables/useApollo')['useApollo']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useBreadcrumb: UnwrapRef<typeof import('./composables/breadcrumb')['useBreadcrumb']>
    readonly useBus: UnwrapRef<typeof import('./composables/useBus')['useBus']>
    readonly useCounterStore: UnwrapRef<typeof import('./stores/example-store')['useCounterStore']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMenuStateStore: UnwrapRef<typeof import('./stores/ui/menu')['useMenuStateStore']>
    readonly useMercureItem: UnwrapRef<typeof import('./composables/mercureItem')['useMercureItem']>
    readonly useMercureList: UnwrapRef<typeof import('./composables/mercureList')['useMercureList']>
    readonly useMetadataStore: UnwrapRef<typeof import('./stores/metadata')['useMetadataStore']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotifications: UnwrapRef<typeof import('./composables/notifications')['useNotifications']>
    readonly usePermisoCreateStore: UnwrapRef<typeof import('./stores/permiso/create')['usePermisoCreateStore']>
    readonly usePermisoDeleteStore: UnwrapRef<typeof import('./stores/permiso/delete')['usePermisoDeleteStore']>
    readonly usePermisoListStore: UnwrapRef<typeof import('./stores/permiso/list')['usePermisoListStore']>
    readonly usePermisoShowStore: UnwrapRef<typeof import('./stores/permiso/show')['usePermisoShowStore']>
    readonly usePermisoUpdateStore: UnwrapRef<typeof import('./stores/permiso/update')['usePermisoUpdateStore']>
    readonly useQuasar: UnwrapRef<typeof import('quasar')['useQuasar']>
    readonly useRoleCreateStore: UnwrapRef<typeof import('./stores/role/create')['useRoleCreateStore']>
    readonly useRoleDeleteStore: UnwrapRef<typeof import('./stores/role/delete')['useRoleDeleteStore']>
    readonly useRoleListStore: UnwrapRef<typeof import('./stores/role/list')['useRoleListStore']>
    readonly useRoleShowStore: UnwrapRef<typeof import('./stores/role/show')['useRoleShowStore']>
    readonly useRoleUpdateStore: UnwrapRef<typeof import('./stores/role/update')['useRoleUpdateStore']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSidebarStore: UnwrapRef<typeof import('./stores/ui/sidebar')['useSidebarStore']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useThemeStateStore: UnwrapRef<typeof import('./stores/ui/ThemeState')['useThemeStateStore']>
    readonly useUserCreateStore: UnwrapRef<typeof import('./stores/user/create')['useUserCreateStore']>
    readonly useUserDeleteStore: UnwrapRef<typeof import('./stores/user/delete')['useUserDeleteStore']>
    readonly useUserListStore: UnwrapRef<typeof import('./stores/user/list')['useUserListStore']>
    readonly useUserSessionStore: UnwrapRef<typeof import('./stores/session')['useUserSessionStore']>
    readonly useUserShowStore: UnwrapRef<typeof import('./stores/user/show')['useUserShowStore']>
    readonly useUserUpdateStore: UnwrapRef<typeof import('./stores/user/update')['useUserUpdateStore']>
    readonly useWatchErrors: UnwrapRef<typeof import('./composables/errors')['useWatchErrors']>
    readonly user: UnwrapRef<typeof import('./models/useEntityFactory')['user']>
    readonly util: UnwrapRef<typeof import('./utils/autoimport/miscellaneous')['util']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}