/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonActionCell: typeof import('./components/common/CommonActionCell.vue')['default']
    CommonBreadcrumb: typeof import('./components/common/CommonBreadcrumb.vue')['default']
    CommonConfirmDelete: typeof import('./components/common/CommonConfirmDelete.vue')['default']
    CommonDataFilter: typeof import('./components/common/CommonDataFilter.vue')['default']
    CommonFormRepeater: typeof import('./components/common/CommonFormRepeater.vue')['default']
    CommonLoading: typeof import('./components/common/CommonLoading.vue')['default']
    CommonToolbar: typeof import('./components/common/CommonToolbar.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    RoleCreate: typeof import('./components/role/RoleCreate.vue')['default']
    RoleForm: typeof import('./components/role/RoleForm.vue')['default']
    RoleList: typeof import('./components/role/RoleList.vue')['default']
    RoleShow: typeof import('./components/role/RoleShow.vue')['default']
    RoleUpdate: typeof import('./components/role/RoleUpdate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserCreate: typeof import('./components/user/UserCreate.vue')['default']
    UserForm: typeof import('./components/user/UserForm.vue')['default']
    UserList: typeof import('./components/user/UserList.vue')['default']
    UserShow: typeof import('./components/user/UserShow.vue')['default']
    UserUpdate: typeof import('./components/user/UserUpdate.vue')['default']
  }
}
